export { default as page2ButtonImg } from "./degree45Arrow.svg";
export { default as title } from "./title.svg";
export { default as title_right } from "./title_right.svg";
export { default as content1 } from "./content1/신난포 1 1.png";
export { default as content1_768 } from "./content1/content1_768.png";
export { default as content1_480 } from "./content1/content1_480.png";
export { default as content2 } from "./content2/신난도_1_bg_removed.png 1.png";
export { default as content2_768 } from "./content2/content2_768.png";
export { default as content2_480 } from "./content2/content2_480.png";
export { default as content3 } from "./content3/신난포도 1 1.png";
export { default as content3_768 } from "./content3/content3_768.png";
export { default as content3_480 } from "./content3/content3_480.png";
